/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_zj_com_ndk_version_2_jni_FootBallJni */

#ifndef _Included_ndk_zj_com_ndk_version_2_jni_FootBallJni
#define _Included_ndk_zj_com_ndk_version_2_jni_FootBallJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_zj_com_ndk_version_2_jni_FootBallJni
 * Method:    ballInfoShow
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_zj_com_ndk_1version_12_jni_FootBallJni_ballInfoShow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
