/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_zj_com_ndk_version_3_jni_BasketBallJni */

#ifndef _Included_ndk_zj_com_ndk_version_3_jni_BasketBallJni
#define _Included_ndk_zj_com_ndk_version_3_jni_BasketBallJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_zj_com_ndk_version_3_jni_BasketBallJni
 * Method:    ballInfoShow
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_zj_com_ndk_1version_13_jni_BasketBallJni_ballInfoShow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
